[package]
name = "tuple_concat_impl"
version = "0.0.0"
authors = ["Waffle <wafflelapkin@gmail.com>"]
description = "helper crate for `fntools` crate that implementa TupleConcat on tuples"
edition = "2018"

[lib]
proc-macro = true

[dependencies]
quote = "1.0.2"
proc-macro2 = "1.0.1"
syn = "1.0"
